language: ruby
services:
  - postgresql
rvm:
  - 2.2.0
env:
  - DB = postgresql
before_script:
  - psql -c 'create database jtandrew_dev;' -U postgres
  - psql -c 'create database jtandrew_test;' -U postgres
  - psql -c 'create database jtandrew_prod;' -U postgres   
script: 
  - bundle exec rake db:create --trace
  - bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake db:create --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
#  - bundle exec rspec spec/
bundler_args: --binstubs=./bundler_stubs
#after_success:
deploy:
  provider: heroku
  api_key: "195ba018-4c56-4ca3-937b-a6a07ff6342b"
  app: sheltered-tor-99662

